name: ForgeRestrictor
main: br.com.finalcraft.forgerestrictor.ForgeRestrictor
version: 1.5.1a
author: [KaiNoMood, EverNife]
loadbefore: [GriefPreventionPlus, WorldGuard, PlotSquared]

commands:
   forgerestrictor:
      description: Manage
      aliases: [fr, fres]

permissions:
    forgerestrictor.manage:
        description: Manage
        default: op
