name: ForgeRestrictor
main: br.com.finalcraft.forgerestrictor.ForgeRestrictor
version: 1.3.5
author: KaiNoMood
loadbefore: [GriefPreventionPlus, WorldGuard]

commands:
   forgerestrictor:
      description: Manage
      aliases: [fr, fres]

permissions:
    forgerestrictor.manage:
        description: Manage
        default: op
