name: FinalForgeRestrictor
main: br.com.finalcraft.finalforgerestrictor.FinalForgeRestrictor
version: 2.0.3
author: [EverNife]
depend: [EverNifeCore]
softdepend: [GriefPreventionPlus, GriefPrevention, WorldGuard, PlotSquared]
api-version: 1.13